"""
Bank-Specific Rule Engines.

Each bank has unique statement layouts, required fields, and known phrases.
Instead of a generic template check, per-bank rules validate that a document
matches the expected format for its declared bank.
"""
import re
from typing import Dict, List, Optional, Tuple


# ── Per-Bank Rule Definitions ────────────────────────────────────────────

BankRules = Dict[str, dict]

BANK_RULES: BankRules = {
    "hdfc": {
        "name": "HDFC Bank",
        "ifsc_prefix": "HDFC",
        "required_fields": [
            "account_number",
            "ifsc",
            "branch",
        ],
        "optional_fields": [
            "customer_id",
            "micr",
            "cif_number",
        ],
        "required_sections": [
            "account summary",
            "transaction details",
        ],
        "section_identifiers": {
            "header": ["hdfc bank", "hdfc", "statement of account"],
            "account_details": ["account no", "account number", "ac no", "a/c no"],
            "transaction_table": ["date", "particulars", "chq", "withdrawal", "deposit", "balance"],
            "summary": ["opening balance", "closing balance", "total credits", "total debits"],
            "footer": ["generated by", "computerised", "statement", "e&oe"],
        },
        "known_phrases": [
            "hdfc bank",
            "hdfc",
            "save & invest",
            "hdfcbank",
        ],
        "known_layout_markers": {
            "header_position": "top",
            "account_details_position": "below_header",
            "transaction_table_position": "middle",
            "summary_position": "bottom",
        },
        "statement_references": [
            "rate of interest",
            "please notify",
            "any discrepancy",
        ],
    },
    "sbi": {
        "name": "State Bank of India",
        "ifsc_prefix": "SBIN",
        "required_fields": [
            "account_number",
            "ifsc",
            "branch",
            "customer_id",
        ],
        "optional_fields": [
            "micr",
            "cif_number",
            "pan",
        ],
        "required_sections": [
            "account summary",
            "transaction details",
        ],
        "section_identifiers": {
            "header": ["state bank of india", "sbi", "statement of account"],
            "account_details": ["account no", "account number", "a/c no", "cif id"],
            "transaction_table": ["date", "particulars", "chq", "withdrawal", "deposit", "balance"],
            "summary": ["opening balance", "closing balance", "total credits", "total debits"],
            "footer": ["generated by", "computerised", "statement", "e&oe"],
        },
        "known_phrases": [
            "state bank of india",
            "sbi",
            "sbiin",
            "स्टेट बैंक ऑफ इंडिया",
        ],
        "known_layout_markers": {
            "header_position": "top",
            "account_details_position": "below_header",
            "transaction_table_position": "middle",
            "summary_position": "bottom",
        },
        "statement_references": [
            "rate of interest",
            "please notify",
            "any discrepancy",
            "नियम एवं शर्तें",
        ],
    },
    "icici": {
        "name": "ICICI Bank",
        "ifsc_prefix": "ICIC",
        "required_fields": [
            "account_number",
            "ifsc",
            "branch",
        ],
        "optional_fields": [
            "customer_id",
            "micr",
            "cif_number",
        ],
        "required_sections": [
            "account summary",
            "transaction details",
        ],
        "section_identifiers": {
            "header": ["icici bank", "icici", "statement of account"],
            "account_details": ["account no", "account number", "a/c no"],
            "transaction_table": ["date", "particulars", "chq", "withdrawal", "deposit", "balance"],
            "summary": ["opening balance", "closing balance", "total credits", "total debits"],
            "footer": ["generated by", "computerised", "statement", "e&oe"],
        },
        "known_phrases": [
            "icici bank",
            "icici",
        ],
        "known_layout_markers": {
            "header_position": "top",
            "account_details_position": "below_header",
            "transaction_table_position": "middle",
            "summary_position": "bottom",
        },
        "statement_references": [
            "rate of interest",
            "please notify",
            "any discrepancy",
        ],
    },
    "axis": {
        "name": "Axis Bank",
        "ifsc_prefix": "UTIB",
        "required_fields": [
            "account_number",
            "ifsc",
            "branch",
        ],
        "optional_fields": [
            "customer_id",
            "micr",
            "cif_number",
        ],
        "required_sections": [
            "account summary",
            "transaction details",
        ],
        "section_identifiers": {
            "header": ["axis bank", "axis", "statement of account"],
            "account_details": ["account no", "account number", "a/c no"],
            "transaction_table": ["date", "particulars", "chq", "withdrawal", "deposit", "balance"],
            "summary": ["opening balance", "closing balance", "total credits", "total debits"],
            "footer": ["generated by", "computerised", "statement", "e&oe"],
        },
        "known_phrases": [
            "axis bank",
            "axis",
        ],
        "known_layout_markers": {
            "header_position": "top",
            "account_details_position": "below_header",
            "transaction_table_position": "middle",
            "summary_position": "bottom",
        },
        "statement_references": [
            "rate of interest",
            "please notify",
            "any discrepancy",
        ],
    },
    "indian bank": {
        "name": "Indian Bank",
        "ifsc_prefix": "IDIB",
        "required_fields": [
            "account_number",
            "ifsc",
            "branch",
        ],
        "optional_fields": [
            "customer_id",
            "micr",
        ],
        "required_sections": [
            "account summary",
            "transaction details",
        ],
        "section_identifiers": {
            "header": ["indian bank", "statement of account"],
            "account_details": ["account no", "account number", "a/c no"],
            "transaction_table": ["date", "particulars", "chq", "withdrawal", "deposit", "balance"],
            "summary": ["opening balance", "closing balance", "total credits", "total debits"],
            "footer": ["generated by", "computerised", "statement", "e&oe"],
        },
        "known_phrases": [
            "indian bank",
        ],
        "known_layout_markers": {
            "header_position": "top",
            "account_details_position": "below_header",
            "transaction_table_position": "middle",
            "summary_position": "bottom",
        },
        "statement_references": [
            "rate of interest",
            "please notify",
            "any discrepancy",
        ],
    },
    "bank of baroda": {
        "name": "Bank of Baroda",
        "ifsc_prefix": "BARB",
        "required_fields": [
            "account_number",
            "ifsc",
            "branch",
        ],
        "optional_fields": [
            "customer_id",
            "micr",
            "cif_number",
        ],
        "required_sections": [
            "account summary",
            "transaction details",
        ],
        "section_identifiers": {
            "header": ["bank of baroda", "baroda", "statement of account"],
            "account_details": ["account no", "account number", "a/c no"],
            "transaction_table": ["date", "particulars", "chq", "withdrawal", "deposit", "balance"],
            "summary": ["opening balance", "closing balance", "total credits", "total debits"],
            "footer": ["generated by", "computerised", "statement", "e&oe"],
        },
        "known_phrases": [
            "bank of baroda",
            "baroda",
            "bob",
        ],
        "known_layout_markers": {
            "header_position": "top",
            "account_details_position": "below_header",
            "transaction_table_position": "middle",
            "summary_position": "bottom",
        },
        "statement_references": [
            "rate of interest",
            "please notify",
            "any discrepancy",
        ],
    },
    "pnb": {
        "name": "Punjab National Bank",
        "ifsc_prefix": "PUNB",
        "required_fields": [
            "account_number",
            "ifsc",
            "branch",
        ],
        "optional_fields": [
            "customer_id",
            "micr",
        ],
        "required_sections": [
            "account summary",
            "transaction details",
        ],
        "section_identifiers": {
            "header": ["punjab national bank", "pnb", "statement of account"],
            "account_details": ["account no", "account number", "a/c no"],
            "transaction_table": ["date", "particulars", "chq", "withdrawal", "deposit", "balance"],
            "summary": ["opening balance", "closing balance", "total credits", "total debits"],
            "footer": ["generated by", "computerised", "statement", "e&oe"],
        },
        "known_phrases": [
            "punjab national bank",
            "pnb",
        ],
        "known_layout_markers": {
            "header_position": "top",
            "account_details_position": "below_header",
            "transaction_table_position": "middle",
            "summary_position": "bottom",
        },
        "statement_references": [
            "rate of interest",
            "please notify",
            "any discrepancy",
        ],
    },
    "union bank": {
        "name": "Union Bank of India",
        "ifsc_prefix": "UBIN",
        "required_fields": [
            "account_number",
            "ifsc",
            "branch",
        ],
        "optional_fields": [
            "customer_id",
            "micr",
        ],
        "required_sections": [
            "account summary",
            "transaction details",
        ],
        "section_identifiers": {
            "header": ["union bank", "union bank of india", "statement of account"],
            "account_details": ["account no", "account number", "a/c no"],
            "transaction_table": ["date", "particulars", "chq", "withdrawal", "deposit", "balance"],
            "summary": ["opening balance", "closing balance", "total credits", "total debits"],
            "footer": ["generated by", "computerised", "statement", "e&oe"],
        },
        "known_phrases": [
            "union bank",
            "union bank of india",
        ],
        "known_layout_markers": {
            "header_position": "top",
            "account_details_position": "below_header",
            "transaction_table_position": "middle",
            "summary_position": "bottom",
        },
        "statement_references": [
            "rate of interest",
            "please notify",
            "any discrepancy",
        ],
    },
    "bank of india": {
        "name": "Bank of India",
        "ifsc_prefix": "BKID",
        "required_fields": [
            "account_number",
            "ifsc",
            "branch",
        ],
        "optional_fields": [
            "customer_id",
            "micr",
        ],
        "required_sections": [
            "account summary",
            "transaction details",
        ],
        "section_identifiers": {
            "header": ["bank of india", "boi", "statement of account"],
            "account_details": ["account no", "account number", "a/c no"],
            "transaction_table": ["date", "particulars", "chq", "withdrawal", "deposit", "balance"],
            "summary": ["opening balance", "closing balance", "total credits", "total debits"],
            "footer": ["generated by", "computerised", "statement", "e&oe"],
        },
        "known_phrases": [
            "bank of india",
            "boi",
        ],
        "known_layout_markers": {
            "header_position": "top",
            "account_details_position": "below_header",
            "transaction_table_position": "middle",
            "summary_position": "bottom",
        },
        "statement_references": [
            "rate of interest",
            "please notify",
            "any discrepancy",
        ],
    },
    "kotak": {
        "name": "Kotak Mahindra Bank",
        "ifsc_prefix": "KKBK",
        "required_fields": [
            "account_number",
            "ifsc",
            "branch",
        ],
        "optional_fields": [
            "customer_id",
            "micr",
        ],
        "required_sections": [
            "account summary",
            "transaction details",
        ],
        "section_identifiers": {
            "header": ["kotak", "kotak mahindra", "statement of account"],
            "account_details": ["account no", "account number", "a/c no"],
            "transaction_table": ["date", "particulars", "chq", "withdrawal", "deposit", "balance"],
            "summary": ["opening balance", "closing balance", "total credits", "total debits"],
            "footer": ["generated by", "computerised", "statement", "e&oe"],
        },
        "known_phrases": [
            "kotak",
            "kotak mahindra",
        ],
        "known_layout_markers": {
            "header_position": "top",
            "account_details_position": "below_header",
            "transaction_table_position": "middle",
            "summary_position": "bottom",
        },
        "statement_references": [
            "rate of interest",
            "please notify",
            "any discrepancy",
        ],
    },
    "yes bank": {
        "name": "Yes Bank",
        "ifsc_prefix": "YESB",
        "required_fields": [
            "account_number",
            "ifsc",
            "branch",
        ],
        "optional_fields": [
            "customer_id",
            "micr",
        ],
        "required_sections": [
            "account summary",
            "transaction details",
        ],
        "section_identifiers": {
            "header": ["yes bank", "statement of account"],
            "account_details": ["account no", "account number", "a/c no"],
            "transaction_table": ["date", "particulars", "chq", "withdrawal", "deposit", "balance"],
            "summary": ["opening balance", "closing balance", "total credits", "total debits"],
            "footer": ["generated by", "computerised", "statement", "e&oe"],
        },
        "known_phrases": [
            "yes bank",
        ],
        "known_layout_markers": {
            "header_position": "top",
            "account_details_position": "below_header",
            "transaction_table_position": "middle",
            "summary_position": "bottom",
        },
        "statement_references": [
            "rate of interest",
            "please notify",
            "any discrepancy",
        ],
    },
}


# ── Field Detection Helpers ─────────────────────────────────────────────

def has_account_number(text: str) -> bool:
    return bool(re.search(r'(?:account\s*(?:no|number|#)|a/c\s*no)[:\s]*([\dX*]+)', text, re.IGNORECASE))


def has_ifsc(text: str) -> bool:
    return bool(re.search(r'[A-Z]{4}0[A-Z0-9]{6}', text))


def has_branch(text: str) -> bool:
    return bool(re.search(r'branch\s*:?\s*\w+', text, re.IGNORECASE))


def has_customer_id(text: str) -> bool:
    return bool(re.search(r'(?:customer\s*(?:id|identification|number)|cif\s*(?:id|number|no))', text, re.IGNORECASE))


def has_micr(text: str) -> bool:
    return bool(re.search(r'micr\s*:?\s*\d{9}', text, re.IGNORECASE))


# ── Bank-Specific Validation Engine ─────────────────────────────────────

def get_bank_rules(bank_name: str) -> Optional[dict]:
    """Get the rule definition for a given bank name."""
    if not bank_name:
        return None
    bank_lower = bank_name.lower().strip()
    return BANK_RULES.get(bank_lower)


def validate_required_fields(text: str, rules: dict) -> List[dict]:
    """Check that all required fields are present in the document."""
    findings = []
    text_lower = text.lower()

    field_checks = {
        "account_number": has_account_number,
        "ifsc": has_ifsc,
        "branch": has_branch,
        "customer_id": has_customer_id,
        "micr": has_micr,
    }

    for field in rules.get("required_fields", []):
        checker = field_checks.get(field)
        if checker and not checker(text):
            findings.append({
                "finding": f"Missing {field.replace('_', ' ').title()}",
                "severity": "MEDIUM",
                "risk_points": 15,
                "field": field,
            })

    return findings


def validate_sections(text: str, rules: dict) -> List[dict]:
    """Check that expected sections are present using section identifiers."""
    findings = []
    text_lower = text.lower()
    section_identifiers = rules.get("section_identifiers", {})

    for section, keywords in section_identifiers.items():
        found = any(kw in text_lower for kw in keywords)
        if not found:
            # Only flag critical sections as missing
            if section in ("header", "transaction_table", "summary"):
                findings.append({
                    "finding": f"Missing {section.replace('_', ' ')} section",
                    "severity": "HIGH" if section == "transaction_table" else "MEDIUM",
                    "risk_points": 20 if section == "transaction_table" else 10,
                    "field": "document_authenticity",
                })

    return findings


def validate_known_phrases(text: str, rules: dict) -> List[dict]:
    """Check that bank-specific phrases appear in the document."""
    findings = []
    text_lower = text.lower()
    known_phrases = rules.get("known_phrases", [])

    found_phrases = [p for p in known_phrases if p.lower() in text_lower]
    if not found_phrases and known_phrases:
        findings.append({
            "finding": f"No {rules['name']}-specific phrases found in document",
            "severity": "MEDIUM",
            "risk_points": 10,
            "field": "document_authenticity",
        })

    return findings


def validate_statement_references(text: str, rules: dict) -> List[dict]:
    """Check for expected statement boilerplate references."""
    findings = []
    text_lower = text.lower()
    refs = rules.get("statement_references", [])
    found_refs = [r for r in refs if r.lower() in text_lower]
    matched = len(found_refs)
    expected = len(refs)
    if expected > 0 and matched / expected < 0.3:
        findings.append({
            "finding": f"Missing standard {rules['name']} statement references ({matched}/{expected} found)",
            "severity": "LOW",
            "risk_points": 5,
            "field": "document_authenticity",
        })

    return findings


def run_bank_rules(text: str, bank_name: str) -> List[dict]:
    """Run all bank-specific validations and return structured findings.

    This replaces the generic validate_bank_template() with a per-bank engine.
    Each bank has its own required fields, sections, phrases, and layout rules.
    """
    rules = get_bank_rules(bank_name)
    if not rules:
        return []

    findings = []
    findings.extend(validate_required_fields(text, rules))
    findings.extend(validate_sections(text, rules))
    findings.extend(validate_known_phrases(text, rules))
    findings.extend(validate_statement_references(text, rules))

    return findings


# ── Transaction Reconstruction ──────────────────────────────────────────

def reconstruct_transaction_flow(
    opening: float,
    credits: float,
    debits: float,
    observed_closing: float,
) -> dict:
    """Build a display-ready transaction reconstruction.

    Returns:
        dict with 'lines' (list of str) and 'status' (match/mismatch)
    """
    expected_closing = opening + credits - debits
    difference = abs(expected_closing - observed_closing)
    is_match = difference <= 1

    lines = []
    lines.append(f"Opening Balance      ₹{opening:>10,.2f}")
    lines.append("")
    lines.append(f"+ Credits            ₹{credits:>10,.2f}")
    lines.append(f"- Debits             ₹{debits:>10,.2f}")
    lines.append("")
    lines.append(f"Expected Closing     ₹{expected_closing:>10,.2f}")
    lines.append(f"Observed Closing     ₹{observed_closing:>10,.2f}")
    lines.append("")

    if is_match:
        lines.append("MATCHED ✓")
    else:
        lines.append(f"Difference           ₹{difference:>10,.2f}")
        lines.append("MISMATCH ✗")

    return {
        "lines": lines,
        "is_match": is_match,
        "expected_closing": expected_closing,
        "observed_closing": observed_closing,
        "difference": difference,
    }
